# WanderingTrades Config ${project.version}
debug: false

# Enable adding trades to natural spawned Wandering Traders
# Summoning Villagers or Traders through commands will bypass this
enabled: true

# should traders be allowed to get trades from more than one
# trade config
allowMultipleSets: true

# Should the plugin remove the original trades from wandering
#    traders
removeOriginalTrades: false