# WanderingTrades Config ${project.version}
debug: false

# Enable adding trades to natural spawned Wandering Traders
# Summoning Villagers or Traders through commands will bypass this
#     requires server restart to turn on/off
enabled: true

# should traders be allowed to get trades from more than one
# trade config
#
#    - when true, the chance in the trade config is the % chance that any
#      trader will get that config
#    - when false, the chance in the trade config is a weight value for
#      picking one trade set per villager
#
# when using false, use disabled configs to insert chances for wandering
# traders with no custom trades
allowMultipleSets: true

# Should the plugin remove the original trades from wandering
#    traders
removeOriginalTrades: false

# should traders summoned using the /wt commands have their trades
# automatically refreshed
#     requires server restart to turn on/off
refreshCommandTraders: false

# how many minutes between trade refreshes, if enabled.
#     tip: setting this to 0 gives a new trade every time you
#          click the trader
refreshCommandTradersMinutes: 5

# false: below is a blacklist of WorldGuard regions for refreshing trades
# true: below is a whitelist of WorldGuard regions for refreshing trades
wgWhitelist: false
wgRegionList:
  - RegionExample
