name: WanderingTrades
version: ${project.version}
main: fun.ccmc.wt.WanderingTrades
api-version: 1.15
description: Customizable Trades for Wandering Traders. Inspired by Vanilla Tweaks

commands:
  wanderingtrades:
    description: WanderingTrades info
    usage: /wanderingtrades